"""Initial Migrate

Revision ID: 724633ec3112
Revises: 
Create Date: 2022-03-13 18:19:19.345183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724633ec3112'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cvli',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('hora', sa.String(), nullable=False),
    sa.Column('ocorrido', sa.String(length=1000), nullable=False),
    sa.Column('local', sa.String(length=50), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fotos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cvli', sa.Integer(), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('senha', sa.String(length=50), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('fotos')
    op.drop_table('cvli')
    # ### end Alembic commands ###
